/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.escuelaing.ieti;

import edu.escuelaing.ieti.config.JwtFilter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class App {

    @Bean
    public FilterRegistrationBean jwtFilter()
    {
        final FilterRegistrationBean registrationBean = new FilterRegistrationBean();
        registrationBean.setFilter( new JwtFilter() );
        registrationBean.addUrlPatterns( "/boards/*" );

        return registrationBean;
    }

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);
    }
}
